### ISSUE TITLE
ValueError: could not convert string '2007_000032' to int32 at row 0, column 1.

### ISSUE THREAD

**Issue by Dream-ai** [JayQine/AMR#13]
I have encountered such an error：
Traceback (most recent call last):
  File "run_sample.py", line 114, in <module>
    step.train_amr.run(args)
  File "/home/stuc/zhx/AMR-main/step/train_amr.py", line 49, in run
    train_dataset = voc12.dataloader.VOC12ClassificationDataset(args.train_list, voc12_root=args.voc12_root,
  File "/home/stuc/zhx/AMR-main/voc12/dataloader.py", line 167, in __init__
    super().__init__(img_name_list_path, voc12_root,
  File "/home/stuc/zhx/AMR-main/voc12/dataloader.py", line 115, in __init__
    self.img_name_list = load_img_name_list(img_name_list_path)
  File "/home/stuc/zhx/AMR-main/voc12/dataloader.py", line 60, in load_img_name_list
    img_name_list = np.loadtxt(dataset_path, dtype=np.int32)
  File "/home/stuc/.conda/envs/amr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1308, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/stuc/.conda/envs/amr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '2007_000032' to int32 at row 0, column 1.
Looking forward to your reply，thank you！！！！

**Comment by ZY-Joying** [comment]
change like these: 1. img_name_list = np.loadtxt(dataset_path, dtype=str) 2. return np.int32(img_name_list)

**Comment by JayQine** [comment]
You should check whether the input of the ''args.train_list'' is correct. The normal input should be ''voc12/train.txt" or "voc12/val.txt".
